git:
  depth: 10

os:
  - linux
  - osx

env:
  global:
    - PATH: ./node_modules/electron-updater-tools/bin:$PATH
    - PUBLISH_BINARY: false
    - NODE_VERSION: iojs
    - ELECTRON_VERSION: 0.28.2

before_install:
  # nvm is not yet supported on osx, manually install
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  # native dependencies
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -qq;
      sudo apt-get install -qq gcc-4.8 g++-4.8 gcc-4.8.multilib g++-4.8-multilib libelf-dev;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8;
    fi

install:
  - nvm install iojs
  # npm dependencies
  - npm install node-gyp -g
  - npm install electron-prebuilt -g
  - npm install

script:
  - npm test