os: Visual Studio 2015 CTP
platform: x64
version: "{build}"

environment:
  target: "0.28.2"
  nodejs_version: "2.2.1"
  publish_binary: false
  bin_dir: ./node_modules/electron-updater-tools/bin

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install -g is-property # workaround until node 2.3.1
  - npm install -g node-gyp
  - npm install -g electron-prebuilt@%target%
  - npm install

test_script:
  - npm test

# Don't actually build.
build: off